# Copyright 2023 RobustMQ Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cluster_name = "mqtt-broker"
broker_id = 2
grpc_port = 29981
placement_center = ["localhost:1228","localhost:2228","localhost:3228"]

[network]
local_ip = "localhost"
tcp_port = 21883
tcps_port = 28883
websocket_port = 28093
websockets_port = 28043
quic_port = 29083
tls_cert = "./config/example/certs/cert.pem"
tls_key = "./config/example/certs/key.pem"

[tcp_thread]
accept_thread_num = 1
handler_thread_num = 10
response_thread_num = 1
max_connection_num = 1000
request_queue_size = 2000
response_queue_size = 2000
lock_max_try_mut_times = 30
lock_try_mut_sleep_time_ms = 50

[auth]
storage_type = "placement"

[prometheus]
enable = true
model = "pull"
port = 9091
push_gateway_server = "localhost:8081"
interval = 10
header = ""

[system]
runtime_worker_threads = 128
default_user = "admin"
default_password = "pwd123"

[storage]
storage_type = "memory"

[log]
log_config = "./config/log-config/mqtt-log4rs.yaml"
log_path = "./robust-data/mqtt-broker-2/logs"
