# Copyright 2023 RobustMQ Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[stdout]
kind = "console"
level = "info"

[server]
kind = "rolling_file"
level = "info"
rotation = "daily"
directory = "./data/broker/logs"
prefix = "server"
suffix = "log"
max_log_files = 50

[http_request]
kind = "rolling_file"
targets = [{ path = "admin_server::server", level = "info" }]
rotation = "daily"
directory = "./data/broker/logs"
prefix = "http_request"
suffix = "log"
max_log_files = 50

[raft]
kind = "rolling_file"
targets = [{ path = "openraft", level = "info" }]
rotation = "daily"
directory = "./data/broker/logs"
prefix = "raft"
suffix = "log"
max_log_files = 50

[meta]
kind = "rolling_file"
targets = [{ path = "meta_service", level = "info" }]
rotation = "daily"
directory = "./data/broker/logs"
prefix = "meta"
suffix = "log"
max_log_files = 50

[engine]
kind = "rolling_file"
targets = [{ path = "storage_engine", level = "info" }]
rotation = "daily"
directory = "./data/broker/logs"
prefix = "engine"
suffix = "log"
max_log_files = 50
