# Copyright 2023 RobustMQ Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cluster_name = "JournalCluster1"
node_id = 1
placement_center = ["127.0.0.1:1228"]

[network]
local_ip = "127.0.0.1"
grpc_port = 2228
tcp_port = 3110
tcps_port = 3111
tls_cert = "./config/example/certs/cert.pem"
tls_key = "./config/example/certs/key.pem"

[system]
runtime_work_threads = 100

[storage]
data_path = [
    "./robust-data/journal-server/storage/data1",
    "./robust-data/journal-server/storage/data2",
]
rocksdb_max_open_files = 10000

[tcp_thread]
accept_thread_num = 1
handler_thread_num = 20
response_thread_num = 2
max_connection_num = 1000
request_queue_size = 2000
response_queue_size = 2000

[prometheus]
enable = false
model = "pull"
port = 9090
push_gateway_server = "127.0.0.1:8081"
interval = 10
header = ""

[shard]
enable_auto_create_shard = false
shard_replica_num = 1
max_segment_size = 1048576

[log]
log_config = "./config/log4rs.yaml"
log_path = "./robust-data/journal-server/logs"
